### ISSUE TITLE
Document/Expand/talk about reporting issues

### ISSUE THREAD

**Issue by cfjedimaster** [lirantal/swagger-lint-api#4]
Forgive the somewhat vague title. So far my work with custom rules have involved simple regex checks, like so:

```
// No curled fancy quote
result = validator.descriptionCompliesWithFunction(value => {
	return !value.match(/’/g)
});
```

But I've got a rule that is a bit more complex. Given a list of words, if the word exists, it must match case. So for example, "Jedi Master" is in the list, and a match must match it exactly, case-wise. So "Jedi master" would be a fail. 

How would I return from my custom function in such a way to report that?

It seems like !value.match(x) implies the negative of an array is good, so no matches. I tried to return an array but it failed to work right.

```
result = validator.descriptionCompliesWithFunction(value => {

	const CAPS = [
              "Jedi Master",
		"Zip Code"
	];	

	CAPS.forEach(c => {
		let regex = new RegExp('\\b'+c+'\\b', 'ig');
		let reResult;

		while( (reResult = regex.exec(value))) {
			if(reResult[0] !== c) {
				 console.log(c+ ' issue with word', value.substr(reResult.index-5, reResult[0].length+5));
				 //return true;
				 //return [reResult[0]];
				 return reResult;
			}
		}

	});
	return [];

});
```

**Comment by lirantal** [comment]
We definitely need better docs around these methods and what is expected to be returned.
That custom function you pass in must return a boolean, either `true` to say that everything is ok and no violation or a `false` if the validation failed.

Furthermore, you don't really need that internal while loop.
If I understand correct your intentions, the CAPS is a list of strings, and if none of them exists in the description that's also ok and the validation will pass, but if the string exists then it must also match the case.

I modified your example here a bit to be used as a test case and perform this logic:

```js
    test('regex test for custom validator', () => {
      const mockSwagger = JSON.parse(JSON.stringify(SwaggerSchemaMock))
      mockSwagger['paths']['/pet']['post']['description'] = 'only a Jedi Master can rule this pet'

      const validator = new DescriptionValidator(mockSwagger)
      const result = validator.descriptionCompliesWithFunction(value => {
        const allowedWords = ['Jedi Master', 'Zip Code']

        let validationPassed = true
        allowedWords.forEach(wordToMatch => {
          // we first of all match the word in the array
          // eslint-disable-next-line security/detect-non-literal-regexp
          let regex = new RegExp('\\b' + wordToMatch + '\\b', 'ig')
          let reResult

          reResult = regex.exec(value)
          if (reResult !== null) {
            // if the word exists in the text, it must match case
            const foundWordMatch = reResult[0]
            if (foundWordMatch !== wordToMatch) {
              validationPassed = false
            }
          }
        })

        return validationPassed
      })

      expect(result).toEqual({valid: true})
    })
```

Does it make more sense now? and is it what you intended to have?

**Comment by cfjedimaster** [comment]
Yes, and the loop was for another linter (textlint) where I could return multiple results - which hopefully this will support soon. :)

**Comment by cfjedimaster** [comment]
btw - I just noticed the readme *clearly* says I should return true or false. My fault.

**Comment by lirantal** [comment]
No worries, this is all great feedback! :)
